name: Automatic service versioning

jobs:
  bump-version:
    name: Bump version on main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: cat package.json
        run: cat ./package.json
      - name: Bump version
        id: version-bump
        uses: ./actions/bump-version.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
  update-jira:
    name: Update Jira ticket
    runs-on: ubuntu-latest
    needs: [bump-version]

    steps:
      - name: Bump Jira
        uses: ./actions/update-jira.yml
