name: Automatic service versioning
description: Automated version bump for npm packages.
runs:
  using: node12
  main: ./versionBump.js

inputs:
  commits:
    description: Git commit messages for the event
    required: true

  currentTag:
    description: The current latest tag for the repo
    required: true

outputs:
  newTag:
    description: The newly created tag